### ISSUE TITLE
too big subrequest response

### ISSUE THREAD

**Issue by ivailop** [nginx/njs#101] opened 2019-02-20 20:44 UTC
In the context of a client POST request, based on the content, we do an **external** `subrequest` (via reverse proxy) to obtain additional attributes.

* nginx.conf
```
...
        location / {
            js_content content_handler;
        }

        location /_attr_proxy {
            proxy_pass          https://api.github.com/repos/s2technologies/testspace.test.ci/git/commits/b64768ec67958f53b2f8cb7ed03f9d40e7eecc1a;
        }
...
```
* content_handler.js
```
function content_handler(r) {
  if (<condition met in r.requestBody>) {
      r.subrequest('/_attr_proxy', '',
        function(res) { r.log(res.responseBody); }
      );
  }
  r.return(200);
}
```

The response from **external** URL, if directly requested, is
```
Content-Type: application/json; charset=utf-8
Content-Length: 1392
```

When done via njs/subrequest it fails with `too big subrequest response`:
```
2019/02/20 19:20:42 [alert] 11714#0: *79 zero size buf in output t:0 r:0 f:0 0000000000000000 0000000000E6B740-0000000000E6B740 0000000000000000 0-0 while sending request to upstream, client: 192.30.252.44, server: somedomain.com, request: "POST /github/companies/1 HTTP/1.1", subrequest: "/_attr_proxy", upstream: "https://192.30.253.116:443/repos/s2technologies/testspace.test.ci/git/commits/b64768ec67958f53b2f8cb7ed03f9d40e7eecc1a", host: "somedomain.com"
2019/02/20 19:20:42 [error] 11714#0: *79 too big subrequest response while sending to client, client: 192.30.252.44, server: somedomain.com, request: "POST /github/companies/1 HTTP/1.1", subrequest: "/_attr_proxy", upstream: "https://192.30.253.116:443/repos/s2technologies/testspace.test.ci/git/commits/b64768ec67958f53b2f8cb7ed03f9d40e7eecc1a", host: "somedomain.com"
```

Are there any `subrequest` response limits? 1392 bites response is very small.

**Comment by drsm** [comment] 2019-02-21 01:05
Hi @ivailop.
> Are there any `subrequest` response limits? 1392 bites response is very small.

Yes they are: [subrequest_output_buffer_size](https://nginx.org/en/docs/http/ngx_http_core_module.html#subrequest_output_buffer_size)

**Comment by ivailop** [comment] 2019-02-21 01:23
After posting the issue I found that setting and tried it but it didn't make a difference. 
Besides that it's `4k|8k` default (as documented) should be big enough to handle my `1.1k` response content.


Could the problem has anything to do with the fact that I'm making a **GET** `subrequest` in the context of a **POST**?

**Comment by drsm** [comment] 2019-02-21 03:42
@ivailop 
Please note, that this is not going to work as expected:
> * content_handler.js
> 
> ```
> function content_handler(r) {
>   if (<condition met in r.requestBody>) {
>       r.subrequest('/_attr_proxy', '',
>         function(res) { r.log(res.responseBody); }
>       );
>   }
>   r.return(200);
> }
> ```
You should use some like this instead (see #31 for details):
```js
function handler(r) {
    if (some) {
        r.subrequest('/whatever', { method: 'GET' }, function(res) {
            r.log(r.responseBody);
            r.return(200);
        });
    } else { 
        r.return(200);
    }
}
```
Also you may want to limit outgoing headers, check [this](https://github.com/nginx/njs/issues/100#issuecomment-464826905) for details
> ```
>         location /_attr_proxy {
>             proxy_pass          https://api.github.com/repos/s2technologies/testspace.test.ci/git/commits/b64768ec67958f53b2f8cb7ed03f9d40e7eecc1a;
>         }
> ```

**Comment by ivailop** [comment] 2019-02-21 20:52
Apparently the outgoing header were causing the problem... I didn't expect the incoming headers to be propagated to the `subrequest`.

Now I see the response content being logged but in the logs there is still the `zero size buf in output` **alert** from above:
```
2019/02/21 20:11:03 [alert] 31166#0: *3288 zero size buf in output t:0 r:0 f:0 0000000000000000 0000000000F8A770-0000000000F8A770 0000000000000000 0-0 while sending request to upstream, client: 192.30.252.35, server: webhook.test.stridespace.com, request: "POST /github/companies/1 HTTP/1.1", subrequest: "/_gh_proxy", upstream: "https://192.30.253.117:443/repos/s2technologies/testspace.test.ci/git/commits/af3105972ed5b1424a87f49b54bda2e93ea8cd71", host: "webhook.test.stridespace.com"
```

**Comment by drsm** [comment] 2019-02-22 10:05
@ivailop did you fix the unconditional ```r.return``` in your codes?

**Comment by xeioex** [comment] 2019-02-22 15:40
@ivailop 

> Apparently the outgoing header were causing the problem... I didn't expect the incoming headers to be propagated to the `subrequest`.

The documentation page will be updated.

>Now I see the response content being logged but in the logs there is still the `zero size buf in output` **alert** from above:

Can you, please, share the debug log? I cannot reproduce it using provided files.

**Comment by ivailop** [comment] 2019-02-25 17:18
@xeioex 
> Can you, please, share the debug log? I cannot reproduce it using provided files.

All I have in the error log are the `zero size buf in output` **alerts**. By debug log do you mean [rebuilding nginx with `--with-debug`](http://nginx.org/en/docs/debugging_log.html)? Unfortunately I can't do that easily because it is being used in our production.

**Comment by xeioex** [comment] 2019-02-25 17:46
@ivailop 

OK, please share your current njs and nginx.conf files.

I can only reprodude zero buf warning by providing empty body value as in:

```js
function github101(r) {                                                                                                          
     r.subrequest('/_attr_proxy', {"body": ""},  function (res) {                                                                
         r.return(200, res.responseBody);                                                                                                                                            
    })                                                                                                                           
}  
```

**Comment by ivailop** [comment] 2019-02-25 20:44
> I can only reprodude zero buf warning by providing empty body value as in:
> 
> ```js
> function github101(r) {                                                                                                          
>      r.subrequest('/_attr_proxy', {"body": ""},  function (res) {                                                                
>          r.return(200, res.responseBody);                                                                                                                                            
>     })                                                                                                                           
> }  
> ```

The explicit empty body could be the reason. While trying to figure out the original problem I when on tweaking the subrequest's `options` argument from simply `''` to explicit `{ method: 'GET', body: '', args: '' },`. 
The question, however, is why am I getting `alert` (is it a critical error?) for that, instead of `warn` (as you stated)?

**Comment by xeioex** [comment] 2019-02-26 06:48
@ivailop 

>The question, however, is why am I getting `alert` (is it a critical error?) for that, instead of `warn` (as you stated)?

It is not critical error, specifically `zero size buf in output` logically is rather warning.  Thanks for reporting it, will be fixed.

**Closed** 2019-02-26 13:33 UTC
