### ISSUE TITLE
Messages are buffered until a different type of message arrives

### ISSUE THREAD

**Issue by mstfldmr** [nginx/njs#45] opened 2018-08-06 15:01 UTC
I am running an njs function to replace a few bytes in MQTT publish packages. the function runs well, but the packages are not transmitted until another type of package arrives. When a MQTT subscribe, unsubscribe, connect etc. message is received all the buffered messages are transmitted at once.

```
function updateTopic(s) {
  if (!s.fromUpstream) {
    if(s.buffer.indexOf("topic") != -1){
      s.buffer = s.buffer.replace("topic", "mopic").toBytes();
    }
  }
  return s.OK;
}
```

**Comment by xeioex** [comment] 2018-08-06 16:19
Hi @mstfldmr,

Could you please confirm that packets are indeed buffered inside nginx?
In addition, please provide:
nginx, njs versions and a more detailed description of your setup.

**Comment by mstfldmr** [comment] 2018-08-07 13:07
Hi @xeioex,

NGINX: 1.14.0
nsj: 0.2.2
Ubuntu: 16.04

I have devices which send their data to the cloud over MQTT. Due to some limitations on the cloud, I need to replace "/" characters with another character in the topic of publish packages. The authentication of devices is done in NGINX with hard-coded tokens in the code, and communication with the cloud is secured with TLS.

replaceTopic() function checks if a package is a Publish package and modifies s.buffer byte string if required.

However, a publish **package is not sent to the cloud immediately if it's modified.** Packages are buffered in NGINX and they are sent to the cloud altogether when a package which is not modified arrives. It can be a ping, subscribe, unsubscribe message or a publish message which does not pass the checks for modification.

Here is my configuration file nginx.conf:

```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

load_module modules/ngx_stream_js_module.so;

events {
    worker_connections  1024;
}

stream {
    js_include mqtt.js;
    js_set     $mqtt_client_id setClientId;

    upstream awsiot {
        server iot.us-east-1.amazonaws.com:8883;
        hash $mqtt_client_id consistent;
    }
    log_format mqtt '$remote_addr [$time_local] $protocol $status $bytes_received'
                '$bytes_sent $upstream_addr $mqtt_client_id'; # Include MQTT ClientId
    server {
        listen 1883;
        preread_buffer_size 1k; # Big enough to read CONNECT packet header
        tcp_nodelay on;
        js_preread getClientId; # Parse CONNECT packet for ClientId
        js_filter replaceTopic;

        proxy_pass awsiot;
        proxy_ssl on;
        proxy_ssl_certificate     nginx-as-client.pem;
        proxy_ssl_certificate_key nginx-as-client.key;
        proxy_ssl_trusted_certificate root-ca-for-awsiot.pem;
        proxy_ssl_verify off;
        proxy_ssl_session_reuse off;

        access_log /var/log/nginx/mqtt_access.log mqtt;
        error_log  /var/log/nginx/mqtt_error.log debug;
    }
}
```

And, here is my Javascript file mqtt.js:

```
var first_message = true;
var client_properties = {
  clientId: "-",
  username: "",
  password: ""
}

var devices = {}
devices["device1"] = "token1";
devices["device2"] = "token2";

function replaceTopic(s) {
  if (!s.fromUpstream) {
    if (isMQTTPublishPackage(s)) {
      if (s.buffer.indexOf("iot-2/type") != -1) {
        s.buffer = s.buffer.replace("iot-2/type", "iot-2-type").toBytes();
      }
    }
  }
}

function getClientId(s) {
  if (!s.fromUpstream) {

    if (s.buffer.toString().length == 0) { // Initial calls may
      s.log("No buffer yet"); // contain no data, so
      return s.AGAIN; // ask that we get called again
    }
    else if (first_message && isMQTTConnectPackage(s)) { // CONNECT is first packet from the client
      first_message = false;
      // Calculate remaining length with variable encoding scheme
      var multiplier = 1;
      var remaining_len_val = 0;
      var remaining_len_byte;
      for (var remaining_len_pos = 1; remaining_len_pos < 5; remaining_len_pos++) {
        remaining_len_byte = s.buffer.charCodeAt(remaining_len_pos);
        if (remaining_len_byte == 0) break; // Stop decoding on 0
        remaining_len_val += (remaining_len_byte & 127) * multiplier;
        multiplier *= 128;
      }

      // Skip fixed header
      var payload_offset = remaining_len_pos + 12;
      // extract ClientId based on length defined by 2-byte encoding
      payload_offset += parseField(s, payload_offset, "clientId")
      // assume no LWT otherwise we need to parse the length and skip those fields
      // extract username
      payload_offset += parseField(s, payload_offset, "username")
      // extract password
      payload_offset += parseField(s, payload_offset, "password")

      if (!isAuthenticated()) {
        return s.ERROR;
      }
    } else {
      //s.log("mmm: not CONNECT package");
    }
  }
  return s.OK;
}

function isAuthenticated() {
  return devices[client_properties["username"]] == client_properties["password"]
}

function isMQTTConnectPackage(s) {
  // package type is 1, using upper 4 bits (00010000 to 00011111)
  var package_type = s.buffer.charCodeAt(0);
  if (package_type >= 16 && package_type < 32) {
    return true;
  } else {
    s.log("No MQTT Connect package - invalid packet type: " + package_type.toString());
    return false;
  }
}
```

**Comment by xeioex** [comment] 2018-08-07 18:02
@mstfldmr  what mqtt client do you use?

Also, I cannot run your code because isMQTTPublishPackage(), parseField() are missing.

**Comment by xeioex** [comment] 2018-08-07 18:09
I wrote a simple tcp client (https://gist.github.com/xeioex/8caa6c28f1c62bbd88bbd3bbeee1b9b6), which sends small chunks of data.

```js
var matched = 0;
function filter(s) {
    s.log("filter 1")
    if (s.fromUpstream || matched) {
        s.log("filter early ret")
        return;
    }

  if (s.buffer.indexOf("CCC") != -1) {
    s.buffer = s.buffer.replace("CCC", "ccc");
    matched = 1;

    s.log("filter matched")
  }
}
```

with it, I do not see any delays for any chunks, including a chunk which is replaced.

**Comment by mstfldmr** [comment] 2018-08-07 21:41
Thanks @xeioex,

a few functions were missing, I added them now.

**Comment by mstfldmr** [comment] 2018-08-07 22:16
Hi @xeioex,

your `filter()` function makes this change only in the first matching message. Following messages are not replaced even if they have the matching string in them.

Why did you introduce this `matched` variable?

**Comment by xeioex** [comment] 2018-08-08 06:15
@mstfldmr  I took the example from http://nginx.org/en/docs/stream/ngx_stream_js_module.html#example (bar() function) and simplified it.

**Comment by xeioex** [comment] 2018-08-08 11:46
@mstfldmr I was able to reproduce your problem, thank you.

Please, try the patch below:

```
# HG changeset patch
# User Dmitry Volyntsev <xeioex@nginx.com>
# Date 1533728731 -10800
#      Wed Aug 08 14:45:31 2018 +0300
# Node ID db628131dca20aa77ea9b7e6f21788dc1841ab0f
# Parent  0139c13eb7786765913e1e9eb70be613d39be903
Fixed forvaring the flush flag while setting s.buffer.

This fixes #45 issue on Github.

diff --git a/nginx/ngx_stream_js_module.c b/nginx/ngx_stream_js_module.c
--- a/nginx/ngx_stream_js_module.c
+++ b/nginx/ngx_stream_js_module.c
@@ -824,6 +824,7 @@ ngx_stream_js_ext_set_buffer(njs_vm_t *v
     ngx_free_chain(c->pool, cl);
 
     b->last_buf = ctx->buf->last_buf;
+    b->flush = ctx->buf->flush;
     b->memory = (value->length ? 1 : 0);
     b->sync = (value->length ? 0 : 1);
     b->tag = (ngx_buf_tag_t) &ngx_stream_js_module;
```

**Comment by mstfldmr** [comment] 2018-08-09 10:32
Thanks @xeioex,

I confirm this patch fixed the problem.

**Comment by xeioex** [comment] 2018-08-09 10:39
@mstfldmr  Glad to hear! Thank you for cooperation.

Please note, this patch will not be committed as is. Currently, I am in progress of refactoring njs stream to make it more similar to node.js style of callbacks and event emitters. Rather, I will include this patch in my current work.

**Comment by xeioex** [comment] 2018-09-11 12:38
Fixed within https://github.com/nginx/njs/commit/7f0756cc5ccbd9521f3832a31102438a2cbacc4f

**Closed by xeioex** 2018-09-11 12:38 UTC
Labels: bug
