### ISSUE TITLE
Unexpected Token on Regex literal "/=" 

### ISSUE THREAD

**Issue by Dissonant-Tech** [nginx/njs#329] opened 2020-07-14 05:15 UTC
I'm getting this error: `nginx: [emerg] SyntaxError: Unexpected token "/="` 

Which is caused by the regexp literal in this function:
```js
function base64Strip(s) {
    return s.replace(/=*$/, '');
}
```

For reference I'm using webpack/babel to compile my node_module dependencies into one file like what is described [here](https://nginx.org/en/docs/njs/node_modules.html). My only dependencies are:

- jwk-to-pem
- jsonwebtoken

**Comment by xeioex** [comment] 2020-07-14 14:37
@Dissonant-Tech  thanks you for reporting the issue, will be fixed.

As a workaround you may use the following code:
```js
function base64Strip(s) {
    return s.replace(new RegExp("=*$"), '');
}
```

The issue is only related to regex literals.

**Comment by Dissonant-Tech** [comment] 2020-07-14 15:26
@xeioex Thanks for the tip, unfortunately that snippet of code is from one of my dependencies and not my own. Either way the workaround might be helpful for others. Thanks again!

**Closed** 2020-07-14 17:23 UTC
Labels: bug, in-progress, parser
