### ISSUE TITLE
Can't copy "Content-Encoding" header in r.headersOut from a subrequest

### ISSUE THREAD

**Issue by tmm360** [nginx/njs#555] opened 2022-06-30 01:10 UTC
I've tested in context of a `js_content` command.

This is the code:
```
        r.headersOut['Content-Encoding'] = "gzip";
        r.warn("content encoding: " + r.headersOut['Content-Encoding']);
```
and this is the output of warn: `content encoding: undefined`

**Comment by xeioex** [comment] 2022-06-30 04:52
Hi @tmm360,

please, share the njs version or the commit for the build from sources.
I cannot reproduce the issue.

**Comment by tmm360** [comment] 2022-06-30 15:21
hi @xeioex. I'm using the last docker image. Anyway, I will try to create a minimal image able to reproduce this.

**Comment by tmm360** [comment] 2022-07-01 15:23
Another example, I've an application that from the subrequest replies with a gzip compressed response. 

Where I'm copying headers, I also choose to print out what values have source and copied with this code:
```
        // Perform subrequest.
        var response = await r.subrequest(
            "/my_sub" + r.uri,
            {
                args: r.variables.args,
                method: r.method
            });

        // Reply filtered response.
        r.headersOut['Content-Type'] = response.headersOut['Content-Type']; //special case. Can't iterate
        for (const h in response.headersOut) {
            r.headersOut[h] = response.headersOut[h];

            r.warn("source " + h + ": " + response.headersOut[h]);
            r.warn("copied " + h + ": " + r.headersOut[h]);
        }
```
and this is the log:
```
2022/07/01 15:16:49 [warn] 35#35: *174 js: copied Content-Type: text/html; charset=utf-8
2022/07/01 15:16:49 [warn] 35#35: *174 js: source Content-Length: 119
2022/07/01 15:16:49 [warn] 35#35: *174 js: copied Content-Length: 119
2022/07/01 15:16:49 [warn] 35#35: *174 js: source Accept-Ranges: bytes
2022/07/01 15:16:49 [warn] 35#35: *174 js: copied Accept-Ranges: bytes
2022/07/01 15:16:49 [warn] 35#35: *174 js: source Content-Encoding: gzip
2022/07/01 15:16:49 [warn] 35#35: *174 js: copied Content-Encoding: undefined
2022/07/01 15:16:49 [warn] 35#35: *174 js: source Vary: Accept-Encoding
2022/07/01 15:16:49 [warn] 35#35: *174 js: copied Vary: Accept-Encoding
2022/07/01 15:16:49 [warn] 35#35: *174 js: source Access-Control-Allow-Origin: *
2022/07/01 15:16:49 [warn] 35#35: *174 js: copied Access-Control-Allow-Origin: *
```
as you can see, every header is copied, except for `Content-Encoding`.

**Comment by tmm360** [comment] 2022-07-01 15:53
Moreover, I've discovered that this has side effects. Probably, I suppose, the header overflow on memory location, because I can find the `gzip` value on different wrong headers. An example:

where I'm invoking the `js_content` (as from my repo) I've also added the instruction `js_header_filter main.logHeaders;`. The method is implemented with:

```
function logHeaders(r) {
    for (const h in r.headersOut) {
        r.warn("log header " + h + ": " + r.headersOut[h]);
    }
}
```

and the log is:

```
2022/07/01 15:34:39 [warn] 35#35: *9 js: source Content-Type: text/html; charset=utf-8
2022/07/01 15:34:39 [warn] 35#35: *9 js: copied Content-Type: text/html; charset=utf-8
2022/07/01 15:34:39 [warn] 35#35: *9 js: source Content-Length: 119
2022/07/01 15:34:39 [warn] 35#35: *9 js: copied Content-Length: 119
2022/07/01 15:34:39 [warn] 35#35: *9 js: source Accept-Ranges: bytes
2022/07/01 15:34:39 [warn] 35#35: *9 js: copied Accept-Ranges: bytes
2022/07/01 15:34:39 [warn] 35#35: *9 js: source Content-Encoding: gzip
2022/07/01 15:34:39 [warn] 35#35: *9 js: copied Content-Encoding: undefined
2022/07/01 15:34:39 [warn] 35#35: *9 js: source Vary: Accept-Encoding
2022/07/01 15:34:39 [warn] 35#35: *9 js: copied Vary: Accept-Encoding
2022/07/01 15:34:39 [warn] 35#35: *9 js: source Access-Control-Allow-Origin: *
2022/07/01 15:34:39 [warn] 35#35: *9 js: copied Access-Control-Allow-Origin: *
2022/07/01 15:34:39 [warn] 35#35: *9 js: log header Content-Type: text/html
2022/07/01 15:34:39 [warn] 35#35: *9 js: log header Content-Length: 171
2022/07/01 15:34:39 [warn] 35#35: *9 js: log header Accept-Ranges: gzip
2022/07/01 15:34:39 [warn] 35#35: *9 js: log header Vary: Accept-Encoding
2022/07/01 15:34:39 [warn] 35#35: *9 js: log header Access-Control-Allow-Origin: *
```
You can see that `gzip` is finished into `Accept-Ranges` header.

**Comment by xeioex** [comment] 2022-07-06 04:09
Hi @tmm360,

Thanks for the report.
I was able to reproduce the issue with nginx/1.23.1

**Comment by xeioex** [comment] 2022-07-06 07:23
Hi @tmm360,

Feel free to test the following patch.

```diff
# HG changeset patch
# User Dmitry Volyntsev <xeioex@nginx.com>
# Date 1657092059 25200
#      Wed Jul 06 00:20:59 2022 -0700
# Node ID 3975f8921f1b630f5a0b0c6d8adad5ec082ca9b5
# Parent  545d2d21dda5c0d49088392ba7a4f648d1e291a8
HTTP: fixed r.headersOut setter for special headers.

The issue was introduced in 5b7676ec600d (0.7.5) when njs module was
adapted to changes in nginx/1.23 related to header structures.

When special headers (Content-Length, Content-Type, Content-Encoding)
were set, the value of the last outgoing header might be overwritten
with a new set value.

This closes #555 issue on Github.

diff --git a/nginx/ngx_http_js_module.c b/nginx/ngx_http_js_module.c
--- a/nginx/ngx_http_js_module.c
+++ b/nginx/ngx_http_js_module.c
@@ -3836,7 +3836,6 @@ ngx_http_js_header_out_special(njs_vm_t 
         return NJS_ERROR;
     }
 
-    h = NULL;
     part = &headers->part;
     header = part->elts;
 
@@ -3861,10 +3860,14 @@ ngx_http_js_header_out_special(njs_vm_t 
         if (h->key.len == v->length
             && ngx_strncasecmp(h->key.data, v->start, v->length) == 0)
         {
-            break;
+            goto done;
         }
     }
 
+    h = NULL;
+
+done:
+
     if (h != NULL && s.length == 0) {
         h->hash = 0;
         h = NULL;
```

**Comment by tmm360** [comment] 2022-07-06 17:50
@xeioex thanks! Do you have a guide on how I can build with this patch? I've never done before.

**Comment by xeioex** [comment] 2022-07-06 19:54
hi @tmm360,

No worry. The bug will be fixed in the next release.
As a workaround you may switch to nginx/1.22 for a while because the issue appeared in nginx/1.23 + njs 0.7.5.

**Comment by tmm360** [comment] 2022-07-06 22:51
Thanks, workaround works!

**Closed** 2022-07-06 23:57 UTC
Labels: bug, nginx-http-module
