### ISSUE TITLE
Failed build

### ISSUE THREAD

**Issue by murlock1000** [nginx/njs#610] opened 2023-02-02 01:48 UTC
Unable to build the latest version with error:
![image](https://user-images.githubusercontent.com/25286623/216211027-48400107-1c75-4bbf-9c4e-0c86ca18e45b.png)

**Comment by xeioex** [comment] 2023-02-02 01:52
Hi @murlock1000,

please, share all the details about the way you build nginx/njs.

**Comment by xeioex** [comment] 2023-02-02 02:19
@murlock1000 

Please, also share the details in text, not image format.

**Comment by danilutkin** [comment] 2023-02-02 11:23
```/usr/src/nginx/njs/nginx/ngx_js_fetch.c: In function 'ngx_js_headers_append':
/usr/src/nginx/njs/nginx/ngx_js_fetch.c:2286:23: error: 'ngx_table_elt_t' {aka 'struct <anonymous>'} has no member named 'next'
 2286 |             ph = &h[i].next;
      |                       ^
/usr/src/nginx/njs/nginx/ngx_js_fetch.c:2287:38: error: 'ngx_table_elt_t' {aka 'struct <anonymous>'} has no member named 'next'
 2287 |             while (*ph) { ph = &(*ph)->next; }
      |                                      ^~
/usr/src/nginx/njs/nginx/ngx_js_fetch.c:2307:6: error: 'ngx_table_elt_t' {aka 'struct <anonymous>'} has no member named 'next'
 2307 |     h->next = NULL;
      |      ^~
/usr/src/nginx/njs/nginx/ngx_js_fetch.c: In function 'ngx_headers_js_get':
/usr/src/nginx/njs/nginx/ngx_js_fetch.c:3210:20: error: 'ngx_table_elt_t' {aka 'struct <anonymous>'} has no member named 'next'
 3210 |             ph = ph->next;
      |                    ^~
/usr/src/nginx/njs/nginx/ngx_js_fetch.c:3226:16: error: 'ngx_table_elt_t' {aka 'struct <anonymous>'} has no member named 'next'
 3226 |         ph = ph->next;
      |                ^~
/usr/src/nginx/njs/nginx/ngx_js_fetch.c:3242:14: error: 'ngx_table_elt_t' {aka 'struct <anonymous>'} has no member named 'next'
 3242 |         if (h->next == NULL) {
      |              ^~
/usr/src/nginx/njs/nginx/ngx_js_fetch.c:3247:14: error: 'ngx_table_elt_t' {aka 'struct <anonymous>'} has no member named 'next'
 3247 |         h = h->next;
      |              ^~
/usr/src/nginx/njs/nginx/ngx_js_fetch.c: In function 'ngx_headers_js_ext_set':
/usr/src/nginx/njs/nginx/ngx_js_fetch.c:3606:23: error: 'ngx_table_elt_t' {aka 'struct <anonymous>'} has no member named 'next'
 3606 |             ph = &h[i].next;
      |                       ^
/usr/src/nginx/njs/nginx/ngx_js_fetch.c:3610:28: error: 'ngx_table_elt_t' {aka 'struct <anonymous>'} has no member named 'next'
 3610 |                 ph = &(*ph)->next;
      |                            ^~
make[1]: Leaving directory '/usr/src/nginx/nginx-1.22.0'
make[1]: *** [objs/Makefile:2900: objs/addon/nginx/ngx_js_fetch.o] Error 1
make: *** [Makefile:10: build] Error 2
```
That's fully repeatable. 
```
docker run -ti --rm alpine:3.12 ash
# Then just put it inside 
apk add build-base ca-certificates patch cmake autoconf automake curl luajit-dev libtool git gcc libc-dev make openssl-dev pcre-dev zlib-dev linux-headers libxslt-dev gd-dev geoip-dev perl-dev libedit-dev mercurial bash alpine-sdk findutils gnupg libmaxminddb-dev
cd /tmp
curl -fSL http://nginx.org/download/nginx-1.22.1.tar.gz -o "/tmp/nginx.tar.gz"
hg clone http://hg.nginx.org/njs
tar xzvf nginx.tar.gz && cd nginx-1.22.1/
./configure --add-dynamic-module=../njs/nginx 
make
```

**Comment by murlock1000** [comment] 2023-02-02 12:51
This issue does not occur in the latest version 0.7.9 which I ended up using as a fix.

I only experienced it when trying to build nginx from source with the latest commit (https://hg.nginx.org/njs/rev/948b167202b2) at the time for nginx 1.20.1 with the command: 

`
./configure --add-module=../njs/nginx 
make
`
Thanks @danilutkin for providing the details in text format.

**Comment by xeioex** [comment] 2023-02-04 05:17
Hi @murlock1000,

Thanks for the report, the issue will be fixed.

The issue is that nginx changed its header structures between 1.22 and 1.23.
So in order to remain compatible with both versions njs have to have separate code for them.
Unfortunately, we do not test upstream of njs with nginx-1.22.
The actual change in njs that cause the issue is here https://github.com/nginx/njs/commit/9551994f82f22d27e04f7fd147b98deba6921687

**Closed** 2023-02-07 03:44 UTC
Labels: build
