### ISSUE TITLE
t=parseInt(t) return NaN

### ISSUE THREAD

**Issue by crasyangel** [nginx/njs#304] opened 2020-04-26 12:18 UTC
./build/njs
```js
interactive njs 0.4.0

v.<Tab> -> the properties and prototype methods of v.

>>var t = "5ea1b0e3"; t=parseInt(t, 16); console.log("rc: " + t);
rc: NaN
undefined
```

**Comment by drsm** [comment] 2020-04-26 15:24
@crasyangel 

Hi!
Looks like a problem with global functions and variable reuse. Duplicate of #289.
`Number` methods work fine:
```js
>> var x = 100500; x = isNaN(x)
true
>> var x = 100500; x = Number.isNaN(x)
false
```

**Closed** 2020-04-27 13:22 UTC
Labels: duplicate
