### ISSUE TITLE
Delete key and then add the same key back cause out of order

### ISSUE THREAD

**Issue by johncrane** [nginx/njs#416] opened 2021-08-18 17:00 UTC
For the following function NJS output “k1=…, k2=…”, instead of “k2=…, k1=…”.
I tried other JS engines such as Node.js and SpiderMonkey. Those engines all generate “k2=…, k1=…”
```
////////////////////////////////////////////////////////////
var obj = {};
obj.k1 = "v1";
obj.k2 = "v2";
// console.log("point 1", JSON.stringify(obj));  // All JS engines print out  "k1=..., k2=..."

delete obj.k1;
obj.k1 = "v1";
console.log("point 2", JSON.stringify(obj)); // NJS print out "K1=..., K2=...". All other JS engines print out "k2=..., k1=..."
////////////////////////////////////////////////////////////
```

**Comment by drsm** [comment] 2021-08-19 11:13
Hi @johncrane 

the issue related to #189

**Comment by xeioex** [comment] 2021-08-20 14:22
Duplicate of #189

**Closed by xeioex** 2021-08-20 14:22 UTC
Labels: duplicate
