### ISSUE TITLE
const support

### ISSUE THREAD

**Issue by renhax** [nginx/njs#297] opened 2020-03-05 03:16 UTC
Hi,

I'm just wondering when const will be supported? In https://github.com/nginx/njs/issues/86#issuecomment-456065081, I saw an interesting optimization that can store const variables into vm->shared->hash_value, will this be included in const implementation?

Thanks,
Renhao

**Comment by xeioex** [comment] 2020-03-05 11:55
According to ES6 const has "let semantic" and the semantic is not implemented yet. We already have [ticket](https://github.com/nginx/njs/issues/105) for this. At this moment the "let" ticket is postponed until parser refactoring is ready.

> will this be included in const implementation?

It turned out to be harder than it seemed initially. Probably it will be implemented as a separate feature.

**Comment by renhax** [comment] 2020-03-05 18:23
Thanks for the update! Is there an issue I can follow for parser refactor?

**Comment by xeioex** [comment] 2020-03-05 19:39
@renhax 

No, this is an internal ticket. But you can track commits related to parser.

**Comment by renhax** [comment] 2020-03-05 20:41
Is there a date we can keep track for parser refactor, let and const? We are trying to do some performance improvement for large global constant, and that optimization I mentioned above seems to be a perfect solution for us.

**Comment by xeioex** [comment] 2020-06-16 08:27
Duplicate of #105.

**Closed by xeioex** 2020-06-16 08:27 UTC
Labels: duplicate, feature
