### ISSUE TITLE
Stack-overflow with some invalid inputs

### ISSUE THREAD

**Issue by HongxuChen** [nginx/njs#156] opened 2019-05-10 05:01 UTC
njs may crash due to stack-overflow with some invalid inputs. These inputs can be files starting with large numbers of repeated `(` or `[`. On my machine, a regularly built njs may segfault with such a file of 8k size.

**update**: Files with only `{` is also affected.

**Comment by xeioex** [comment] 2019-05-10 06:27
@HongxuChen 

Thanks for your report, the issue seems to be a duplicate of #146

**Closed by xeioex** 2019-05-10 06:27 UTC
