### ISSUE TITLE
Crypto pseudo-random integers

### ISSUE THREAD

**Issue by cttr-dev** [nginx/njs#275] opened 2019-12-11 09:37 UTC
Hello. Please, add able to generate cryptographically secure pseudo-random integers.

e.g:
https://developer.mozilla.org/ru/docs/Web/API/RandomSource/getRandomValues
https://www.php.net/manual/en/function.random-int.php

**Comment by xeioex** [comment] 2020-06-16 08:25
Duplicate of #251.

**Closed by xeioex** 2020-06-16 08:25 UTC
Labels: crypto, duplicate, feature
